# Generated by Django 5.1.3 on 2024-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.IntegerField(default=0)),
                ('session', models.IntegerField(default=0)),
                ('graduated', models.IntegerField(default=0)),
            ],
        ),
    ]
