# Generated by Django 5.1.3 on 2024-11-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_alter_status_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table=None,
        ),
    ]
