# Generated by Django 5.1.3 on 2024-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle1', models.CharField(max_length=50)),
                ('description1', models.CharField(max_length=250)),
            ],
        ),
    ]
