# Generated by Django 5.1.3 on 2024-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_card1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle2', models.CharField(max_length=50)),
                ('description2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Card3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle3', models.CharField(max_length=50)),
                ('description3', models.CharField(max_length=250)),
            ],
        ),
    ]
