# Generated by Django 5.1.3 on 2024-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0006_card2_card3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('postal_address', models.CharField(max_length=100)),
                ('primary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('primary_year', models.CharField(blank=True, max_length=4, null=True)),
                ('secondary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('secondary_year', models.CharField(blank=True, max_length=4, null=True)),
                ('course', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('intake', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
