# Generated by Django 5.1.3 on 2024-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0007_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('entery_requirements', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=30)),
                ('exam_body', models.CharField(max_length=50)),
                ('mode_of_study', models.CharField(max_length=50)),
            ],
        ),
    ]
