# Generated by Django 5.1.3 on 2024-12-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0014_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='primary_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='secondary_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_admission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='onlineapp.finance')),
            ],
        ),
    ]
