# Generated by Django 5.1.3 on 2024-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0015_alter_application_primary_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Engineering', 'Engineering')], default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='student',
            name='yoa',
            field=models.PositiveIntegerField(default='Unknown', verbose_name='Year of Admission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
