# Generated by Django 5.1.3 on 2024-12-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0016_remove_student_user_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='yoa',
            field=models.PositiveIntegerField(default=2024, verbose_name='Year of Admission'),
        ),
    ]
