# Generated by Django 5.1.3 on 2024-12-06 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0019_remove_student_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adm_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='yoa',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(default='unknown', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
