# Generated by Django 5.1.3 on 2024-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0020_remove_student_adm_number_remove_student_yoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_number',
            new_name='adm_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year_of_admission',
            new_name='yoa',
        ),
    ]
