# Generated by Django 5.1.3 on 2024-12-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0017_alter_student_yoa'),
        ('onlineapp', '0021_rename_admission_number_student_adm_number_and_more'),
    ]

    operations = [
    ]
