# Generated by Django 5.1.3 on 2024-12-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0023_alter_student_yoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Admission Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='yoa',
            field=models.IntegerField(verbose_name='Year of Admission'),
        ),
    ]
