# Generated by Django 5.1.3 on 2024-12-06 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0024_remove_student_full_name_student_admission_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_number',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
